  nums= [1 , 3, -1, -3, 5, 3, 6, 7];
k = 3;

// Output result = [3, 3, 5, 5, 6, 7]

// sliding window is work in the k number of elemetn in the array find max element and store in a another array


const slidingWindow = function (nums, k){
        let result = [];
        const n = nums.length;

        for(let i = 0; i<= n- k; i++){
            let max = nums[i]
            for(let j = 1; j<k; j++){
                if(nums[i+j] > max){
                    max = nums[i+j]
                }
            }
            result.push(max)
        }
        return result
}
console.log(slidingWindow(nums, k))